export const endpoints = {
    REGIONSDROPDOWN: '/settings/sales/rates/express/contract/dropdowns/regions',
    TRIPSBIKEGRID:'/settings/sales/rates/express/contract/dropdowns/region/trips/bike',
    TRIPSVANGRID:'/settings/sales/rates/express/contract/dropdowns/region/trips/van',
    CREATERATECARD:'/settings/salesSettings/rates/express/contract/rateCard',
    REGIONS: 'settings/salesSettings/rates/express/contract/region',
    RATECARD:'/settings/salesSettings/rates/express/contract/regionRateCards',
    REGIONRATES:'/settings/salesSettings/rates/express/contract/rateCard',
    ADDITIONALSURCHARGES:'/settings/salesSettings/rates/express/contract/rateCards/additionalSurcharges',
    SURCHARGES:'/settings/salesSettings/rates/express/contract/rateCards/surcharges',
    BIKERATETRIPS:'/settings/salesSettings/rates/express/contract/rateCards/normal/bike/trips',
    BIKERATERATES:'/settings/salesSettings/rates/express/contract/rateCards/normal/bike/rates',
    BIKECUSVANJOB:'/settings/salesSettings/rates/express/contract/rateCards/normal/bike/bikeCustomerVanJob',
    DELETEADDLSURCHARGE:'/settings/salesSettings/rates/express/contract/rateCards/additionalSurcharges',
    DELETENORMALBIKETRIPS:'/settings/salesSettings/rates/express/contract/rateCards/normal/bike/trips',
    CREATENORMALBIKERATES:'/settings/salesSettings/rates/express/contract/rateCards/normal/bike/rates',
    DELETENORMALBIKERATES:'/settings/salesSettings/rates/express/contract/rateCards/normal/bike/rates',
    CREATENORMALVANRATES:'/settings/salesSettings/rates/express/contract/rateCards/normal/van/rates',
    DELETENORMALVANRATES:'/settings/salesSettings/rates/express/contract/rateCards/normal/bike/rates',
    DELETENORMALVANTRIPS:'/settings/salesSettings/rates/express/contract/rateCards/normal/van/trips',
    CREATEMULTITIERVANJOB:'/settings/salesSettings/rates/express/contract/rateCards/normal/van/multiTireRate/jobCount',
    CREATEMULTITIERQUANTITY:'/settings/salesSettings/rates/express/contract/rateCards/normal/van/multiTireRate/quantity',
    DELETEMULTITIERVANJOB:'/settings/salesSettings/rates/express/contract/rateCards/normal/van/multiTireRate/jobCount',
    DELETEMULTITIERQUANTITY:'/settings/salesSettings/rates/express/contract/rateCards/normal/van/multiTireRate/quantity',
    CREATEECOMMERCEDELIVERY:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/deliveryType/bike',
    CREATEECOMBIKERATES:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/deliveryTypes/rate/bike',
    DELETEECOMMERCEDELIVERY:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/deliveryType/bike',
    DELETEECOMBIKERATES:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/deliveryTypes/rate/bike',
    CREATEECOMMERCEVANDELIVERY:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/deliveryType/van',
    CREATEECOMVANRATES:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/deliveryTypes/rate/van',
    CREATEECOMVANQUANTITY:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/van/deliveryTypes/chargeByQuantities/rates',
    DELETEECOMVANDELIVERY:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/deliveryType/Van',
    DELETEECOMVANDELIVERYRATES:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/deliveryTypes/rate/van',
    DELETEECOMVANQUANTITYBOXES:'/settings/salesSettings/rates/express/contract/rateCards/eCommerce/van/deliveryTypes/chargeByQuantities/rates',
    CREATENORMALBIKETRIPS:'/settings/salesSettings/rates/express/contract/rateCards/normal/bike/trips',
    CREATENORMALVANTRIPS:'/settings/salesSettings/rates/express/contract/rateCards/normal/van/trips',
    CREATENORMALVANQUANTITYBOXES:'/settings/salesSettings/rates/express/contract/rateCards/normal/van/twoTireRate/quantities/rates'
} 